name = "blog"
compatibility_date = "2025-07-06"

[build]
command = "hugo"

[assets]
directory = "./public"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[observability.logs]
enabled = true